sudo: required
dist: trusty
before_install:
- sudo apt-get install -y --no-install-recommends
    texlive-fonts-recommended texlive-generic-recommended
    texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
    texlive-base texlive-pictures texlive-lang-cyrillic texlive-science texlive-generic-extra
    pgf
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/diploma.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/diploma.tex

    
