cc_binary(
    name = "mrss-simulator",
    srcs = glob(["*.h", "*.cpp"]),
    deps = [
        "@simgrid_headers//:simgrid",
        "@simgrid_lib//:libsimgrid",
        "@yaml-cpp//:yaml-cpp"
    ],
)

