version: 1

simulation:
  mapper:
    input_size: 5000000
  reducer:
    input_size: 4000000

stages:
  mapper:
    type: mapper
    executable: ./mapper
    input: ./mapper_input_sample
  reducer:
    type: reducer
    after: mapper
    executable: ./reducer
    input: ./reducer_input_sample
